name: Build

on: [push]

defaults:
  run:
    working-directory: app

jobs:
  Build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        architecture:
          - 'x64'
          - 'x86'
        python-version:
          - '3.x'

    runs-on: ${{ matrix.os }}

    env:
      APP_NAME: app-${{ matrix.os }}-$${{ matrix.architecture }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.architecture }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: ${{ matrix.architecture }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pytest
          [ -f requirements.txt ] && pip install -r requirements.txt

      - name: Test with pytest
        run: pytest

      - name: Build with pyinstaller
        run: pyinstaller --onefile --name=$APP_NAME main.py

      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: dist/$APP_NAME
