name: Build

on: [push]

defaults:
  run:
    working-directory: app

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    # env:
    #   sep: ${{ matrix.os == "windows-latest" && '\' || '/' }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip pyinstaller pytest
          pip install -r requirements.txt

      - name: Test with pytest
        run: pytest

      - name: Build with pyinstaller
        run: pyinstaller --onefile --name=app main.py

      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: app-${{ matrix.os }}
          # path: ${{ github.workspace }}${{ env.sep }}app${{ env.sep }}dist${{ env.sep }}app
          path: ${{ join([github.workspace, 'app', 'dist', 'app'], runner.os == "Windows" && '\' || '/') }}
          if-no-files-found: error
