name: Build

on: [push, pull_request]

defaults:
  run:
    working-directory: app

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2

      - name: Setup | Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup | Dependencies
        run: |
          python -m pip install --upgrade pip pyinstaller pytest
          pip install -r requirements.txt

      - name: Test | pytest
        run: pytest

      - name: Build | pyinstaller
        run: pyinstaller --onefile --name=app main.py

      - name: Post Build | Prepare artifacts (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          move-item dist/app ${{ github.workspace }}/app-${{ matrix.os }}

      - name: Post Build | Prepare artifacts (UNIX)
        if: matrix.os != 'windows-latest'
        run: |
          mv dist/app ${{ github.workspace }}/app-${{ matrix.os }}

      - name: Deploy | Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-${{ matrix.os }}
          path: app-${{ matrix.os }}

      # - name: Upload release asset
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
