name: Build

on: [push]

defaults:
  run:
    working-directory: app

jobs:
  Build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    env:
      APP_NAME: app-${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.7'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip pyinstaller pytest
          python -m pip install -r requirements.txt

      - name: Test with pytest
        run: pytest

      - name: Build with pyinstaller
        run: |
          pyinstaller --onefile --name=$APP_NAME main.py
          echo "dist files"
          ls dist
          echo "path"
          echo dist/${{ env.APP_NAME }}

      - name: Upload executable
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: dist/*
          if-no-files-found: error
