name: Build

on: [push, pull_request]

defaults:
  run:
    shell: bash
    working-directory: app

jobs:
  Build:
    name: Build release binaries

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip pyinstaller pytest
          pip install -r requirements.txt

      - name: Test with pytest
        run: pytest

      - name: Build with pyinstaller
        run: pyinstaller --onefile --name=app main.py

      - name: Prepare artifacts
        working-directory: ${{ github.workspace }}
        run: mv app/dist/app app-${{ matrix.os }}

      - name: Debug artifacts
        working-directory: ${{ github.workspace }}
        run: |
          echo "pwd:"
          pwd
          echo "ls:"
          ls
          echo "find .:"
          find .

      - name: Deploy artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-${{ matrix.os }}
          path: app-${{ matrix.os }}
          if-no-files-found: error

      # - name: Upload release asset
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
